#配布とかするコマンド
command /start:
    permission: op
    trigger:
        loop all players:
            set gravity of loop-player to on
            set loop-player's gamemode to survival
            abilitytoggle(true, loop-player)
            ability(0, loop-player)
            set {_p} to name of loop-player
            send "あなたの能力は ""%{ability::players::%{_p}%}%§r""です%nl%能力の詳細はインベントリの頭防具でいつでも確認できます" to loop-player
            send "切り替え可能能力は""/ability""または""/a""で切り替えることができます" to loop-player
        
#能力切り替え
command /ability:
    aliases: /a
    trigger:
        abilitytoggle(false, player)
function abilitytoggle(forcedisable: boolean, player: player):
    if abilityistrue({_player}) is no:
        exit 1 sections if {_forcedisable} is true 
        set metadata value "toggle" of {_player} to true
        send "能力の発動を有効化" to {_player}
        set {_player}'s gamemode to spectator if abilityof({_player}) is {ability::3} #能力3スペク化
        stop
    else:
        set metadata value "toggle" of {_player} to false
        send "能力の発動を無効化" to {_player}
        disallow flight to {_player}
        set {_player}'s gamemode to survival if abilityof({_player}) is {ability::3} #能力3スペク化
        stop
#能力1飛行
on jump:
    abilityistrue(event-player) is yes
    allow flight to event-player if abilityof(event-player) is {ability::1}
on food bar change:
    abilityistrue(event-player) is yes
    player's food level < 4
    set the player's food level to 4 if abilityof(player) is {ability::1}
#能力2ワンパン
on damage by player:
    abilityistrue(attacker) is yes
    set victim's health to 0 if abilityof(attacker) is {ability::2}
#能力5不死身
on death of player:
    abilityof(victim) is {ability::5}
    cancel event
    add potion effect of slowness of tier 4 without particles for 5 seconds to potion effects of victim
on teleport:
    cancel event if teleport cause is spectator
#能力4アドベ化
function ability4(player: player):
    abilityistrue({_player}) is yes
    abilityof({_player}) is {ability::4}
    loop all players in radius 16 of {_player}:
        loop-player is not {_player}
        metadata value "adv" of loop-player is not true
        set metadata value "adv" of loop-player to true
        set loop-player's gamemode to adventure
        while all players in radius 16 of {_player} contains loop-player:
            wait 1 tick
            stop loop if abilityistrue({_player}) is not yes
            stop loop if abilityof({_player}) is not {ability::4}
        set loop-player's gamemode to survival
        set metadata value "adv" of loop-player to false
#能力6爆破
on block damage:
    abilityistrue(player) is yes
    abilityof(player) is {ability::6}
    make an explosion of force 1
on damage:
    if damage cause is entity explosion or block explosion:
        cancel event if abilityof(victim) is {ability::6}
    attacker is player   
    abilityistrue(attacker) is yes
    abilityof(attacker) is {ability::6}
    make an explosion of force 1 at victim 
#能力7加速
function ability7(player: player):
    abilityistrue({_player}) is yes
    abilityof({_player}) is {ability::7}
    metadata value "Atime" of {_player} is not true
    set metadata value "Atime" of {_player} to true
    command "/tick rate 200"
    loop 15*20 time:
        wait 10 tick
        stop loop if abilityistrue({_player}) is not yes
        stop loop if abilityof({_player}) is not {ability::7}
    command "/tick rate 20"
    addcooltime({_player}, 30)
#Cooltime追加
function addcooltime(player: player, time: number):
    loop {time}*20 time:
        wait 1 tick
        abilityistrue({_player}) is yes
        abilitytoggle(true, {_player})
        send "クールタイム中なので発動に失敗しました" to {_player}
    send action bar "§4能力の再使用が可能です。" to {_player}
    if abilityof({_player}) is {ability::7}:
        set metadata value "Atime" of {_player} to false

on food bar change:
    set the player's food level to 10
    abilityof(player) is {ability::8}
#ハイペ
on rightclick:
    player's tool is {item::1}
    loop 10 time:
        block infront of player is air or cave air or void air
        teleport player infront of player
    make a fake explosion at player
    loop all entities in radius 10 of player:
        loop-entity is not player
        make player attack loop-entity
    add potion effect of absorption of tier 2 for 10 second to potion effects of player if amplifier of absorption of player is not 2 
on damage:
    attacker is player
    attacker's tool is {item::1}
    cancel event
    damage victim by final damage
    set victim's target to attacker
    #ドロップ10倍キャンペーン
on death:
    attacker is player
    victim is not player
    loop 10 time:
        give drops to attacker
#能力設定
on load:
    set {ability::1} to "飛行 / §k_＿_＿§r𝕏§k_＿_＿§r"
    set {ability::2} to "ワンパン / §cOne Tap Killer"
    set {ability::3} to "スペク化 / §lA Invincible and Invisible"
    set {ability::4} to "アドベ化 / §2§lEverybody an Adventurer"
    set {ability::5} to "不死身 / §4§lDEATH is Cancelled"
    set {ability::6} to "爆弾魔 / §a§lIch bin Creeper"
    set {ability::7} to "時間加速 / §e Accerarate Worlds"
    set {ability::8} to "空島出身者 / §bSkyBlocker"
    set {item::1} to iron sword of smite 7 named "Hyperion" with lore "§7ItemAbility(右クリック)%nl%%nl%§8ShadowWarp%nl%§7正面に最大10mテレポート%nl%§8Implosion%nl%§7テレポート先で半径10m以内にいるエンティティに%nl%§7ダメージを与える爆破を起こす%nl%§8WitherShield%nl%§7金ハートが10秒つく%nl%§0受け渡し不可"

#能力配布
function ability(n: number ,p :player):
    set {_p} to name of {_p}
    if {_n} is 0:
        set {ability::players::%{_p}%} to random element out of {ability::*}
    else:
        set {ability::players::%{_p}%} to {ability::%{_n}%}
    giveitem({_p})
function giveitem(player: player):
    if abilityof({_player}) is {ability::8}:
        give {item::1} to {_player}
#能力識別
function abilityof(player: player) :: text:
    set {_p} to name of {_player}
    return {ability::players::%{_p}%}
function abilityistrue(player: player) :: boolean:
    return yes if metadata value "toggle" of {_player} is true
    return no if metadata value "toggle" of {_player} is not true
function abilityslore(ability: text) :: text:
        return "%nl%§8あなたは空を飛ぶことができます。%nl%%nl%§7切り替え可能能力：飛行%nl%§8有効の間クリエ飛行ができ落下ダメージが無くなり%nl%満腹度が4未満にならなくなります。%nl%%nl%§7常時発動能力：無し" if {_ability} is {ability::1}
        return "%nl%§cあなたは生物を一撃で殺すことができます。%nl%%nl%§7切り替え可能能力：一撃必殺%nl%§8有効になっている間エンティティに攻撃すると%nl%§8攻撃されたエンティティの体力が0に設定されます%nl%%nl%§7常時発動能力：無し" if {_ability} is {ability::2}
        return "%nl%§fあなたは幽霊のようになることができます。%nl%%nl%§7切り替え可能能力：スペクテイターモード%nl%§8有効化するとゲームモードがスペクテイターになります。%nl%無効化するとサバイバルになります。%nl%%nl%§7常時発動能力：無し" if {_ability} is {ability::3}
        return "%nl%§2あなたの周りのプレイヤーはブロックの設置や破壊ができなくなります。%nl%%nl%§7切り替え可能能力：アドベンチャーモード%nl%§8有効化されている間半径16メートル以内の%nl%§8プレイヤーのゲームモードはアドベンチャーになります。%nl%効果は対象が範囲を出るかこちらが能力を無効にするまで続きます%nl%%nl%§7常時発動能力：無し" if {_ability} is {ability::4}
        return "%nl%§4あなたは死ぬことがないです。%nl%%nl%§7切り替え可能能力：無し%nl%§7常時発動能力：不死%nl%§8しっかりダメージは受けますが体力が0になると完全回復します§0(痛い....)" if {_ability} is {ability::5}
        return "%nl%§aあなたは生物やブロックを爆発させることができます。%nl%%nl%§7切り替え可能能力：爆破%nl%§8エンティティにダメージを与えると爆発します%nl%§8ブロックを殴ると爆発します%nl%§0あと他の能力は/の後は英語なのになぜこれはドイツ語なのか。" if {_ability} is {ability::6}
        return "%nl%§eあなたはプレイヤー以外のすべてを加速させることができます。%nl%%nl%§7切り替え可能能力：時間加速%nl%有効化すると15秒間時間が加速し無敵になります。%nl%効果が終了するか手動で無効化するとしばらく使えなくなります。" if {_ability} is {ability::6}
        return "%nl%§bあなたは別の世界からやってきました。%nl%§3別の世界のプレイヤーの性質とアイテムを持っています。%nl%%nl%§7専用アイテム：Hyperion%nl%§7常時発動能力：Skyblock%nl%§8空腹にならない"

every 1 tick:
    loop all players:
        set helmet of loop-player to stone button named "§7あなたの能力は""%abilityof(loop-player)%§7です" with lore abilityslore(abilityof(loop-player))
        ability4(loop-player)
        ability7(loop-player)
on inventory click:
    if event-slot is helmet of player:
        cancel event
        abilitytoggle(false, player)        
on death of player:
    remove all stone button from the drops
    remove all {item::1} from drops
    force victim to respawn
    wait 1 tick
    giveitem(victim)
on kick:
    cancel event
command /test <integer> <player>:
    permission: op
    trigger:
        ability(arg-1, arg-2)
        send "あなたの能力は ""%abilityof(arg-2)%§r""です%nl%能力の詳細はインベントリの頭防具でいつでも確認できます" to arg-2
        send "切り替え可能能力は""/ability""または""/a""で切り替えることができます" to arg-2
on item damage:
    lore of event-item contains "§0受け渡し不可"
    cancel event
on drop:
    lore of event-item contains "§0受け渡し不可"
    cancel event 
on inventory click:
    lore of event-item contains "§0受け渡し不可"
    cancel event if player's current inventory is not player's inventory